### ISSUE TITLE
License of this project

### ISSUE THREAD

**Issue by masaha03** [scheuchzer/glassfish-jdbc-realm-salted#1]
Please tell me the license of this project. I want to use this in my oss project!

**Comment by scheuchzer** [comment]
What license do you prefer? Is apache license v2 ok for you?

**Comment by masaha03** [comment]
Absolutely OK!

**Comment by scheuchzer** [comment]
License has been added and there's a new version:
<dependency>
    <groupId>com.java-adventures.glassfish.realm.salted</groupId>
    <artifactId>glassfish-jdbc-realm-salted</artifactId>
    <version>0.2.2</version>
</dependency>

**Comment by masaha03** [comment]
Thank you!
